### ISSUE TITLE
[Question] The explode animation when typing characters don't work, is it because it have no such animation ?

### ISSUE THREAD

**Issue by Atanacius** [negipo/cute-cursor#8]
I ask that, because, what had made me install that Atom package was indeed the explode animation.

It have only a flash rainbow background, not cute as the actual preview picture seems say...

I feel sad and disappointed if it's just a hanging method in order to make download the package.

Anyway, my question also will be: is there any version planned to add the "explode" effect ?
I like it!

EDIT: To all people, the explode effect is in this package: https://atom.io/packages/activate-power-mode

**Comment by hmsk** [comment]
Indeed, that effect is by Activate Power Mode you mentioned

**Comment by hmsk** [comment]
Noted on README, thanks for pointing ✨

**Comment by Atanacius** [comment]
You're welcome :)
